text_commands:
  lactose_free: "Безлактозные продукты"
  gluten_free: "Безглютеновые продукты"

description:
  start: "Привет! Я помогу составить тебе рацион питания. Выбери следующий шаг."
  type_product: "Отлично, выберите одну из следующих категорий"
  try_again: "Попробуйте заново"