text_commands:
  lactose_free: "Безлактозные продукты"
  gluten_free: "Безглютеновые продукты"
  back_menu: "Главное меню"

description:
  start: "Привет \U0001F44B\n\nЧем я смогу тебе помочь? \U0001F914 Со мной ты сможешь составить рацион питания из продуктов, которые не содержат глютен или лактозу.\n\nВыбери один из видов продукции, чтобы продолжить\U0001F447"
  type_product: "Отлично, выбери одну из следующих категорий \U0001F603"
  try_again: "Введена неверная команда, попробуй заново \U0001F504"
  back_menu: "Выбери один из видов продукции, чтобы продолжить\U0001F447"