text_commands:
  lactose_free: "Безлактозные продукты"
  gluten_free: "Безглютеновые продукты"
  back_menu: "Назад"

description:
  start: "Привет! Я помогу составить тебе рацион питания. Выберите следующий шаг"
  type_product: "Отлично, выберите одну из следующих категорий"
  try_again: "Попробуйте заново"
  back_menu: "Вы вернулись в главное меню. Выберите тип продукта"